networks:
  pdnode-network:
    driver: bridge

services:
  db:
    image: postgres:16-alpine
    container_name: pdnode-db
    restart: always
    networks:
      - pdnode-network
    environment:

      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}" ]
      interval: 5s
      timeout: 5s
  redis:
    image: redis:7-alpine
    container_name: pdnode-redis
    restart: always
    env_file:
      - .env
    networks:
      - pdnode-network
    volumes:
      - ./docker-data/redis:/data

  app:
    image: ghcr.io/pdnode-team/account-backend:latest
    container_name: pdnode-app
    restart: always
    networks:
      - pdnode-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      NODE_ENV: production
    ports:
      # if you want, you can change the number
      # Host:Container
      - 3333:${PORT}
    command: >
      sh -c "node ace migration:run --force && node bin/server.js"
